### PR TITLE
Encoding in ascii

### PR DESCRIPTION
**Pull request by jerrydark**

### CODE REVIEW

**Comment by kryptxy** [comment]
How is it useful? Please provide some description.

**Comment by jerrydark** [comment]
This replaces uninterpretable characters by `?` so that show_output wouldnt cause unicodeErrors.

**Comment by kryptxy** [comment]
In what scenario did you get UnicodeError? Linux systems are able to print Unicode characters fine. Same for OSX if I am not wrong.
I got UnicodeError in windows, which is resolved as [here](https://github.com/kryptxy/torrench/blob/master/torrench/modules/thepiratebay.py#L175). 

Please provide a more detailed info about this PR. 
If you got an error, please attach the log file so that I that I can reproduce that error.

**Comment by jerrydark** [comment]
I think it's more of a python issue.
I'm on Archlinux and here's a example image.

2017-10-15-223958_736x434_scrot

same error can be reproduced on `-x`, `-n` and linuxtracker(no arg) when searching term `test`

**Comment by jerrydark** [comment]
`2017-10-15 23:02:46,633: (__main__.py->main #30): [DEBUG] - Torrench started.
2017-10-15 23:02:46,633: (Torrench.py->define_args #48): [DEBUG] - command-input: ['/usr/bin/torrench', '-t', 'test']
2017-10-15 23:02:46,635: (Config.py->file_exists #43): [DEBUG] - Config file exists and enabled!
2017-10-15 23:02:46,635: (Torrench.py->resolve_args #173): [DEBUG] - using thepiratebay
2017-10-15 23:02:46,635: (Torrench.py->resolve_args #178): [DEBUG] - Input title: [test] ; page_limit: [1]
2017-10-15 23:02:46,636: (Config.py->get_proxies #53): [DEBUG] - getting proxies for 'tpb'
2017-10-15 23:02:47,078: (Common.py->http_request #91): [DEBUG] - returned status code: 200 for url https://proxybay.one
2017-10-15 23:02:47,099: (Config.py->get_proxies #75): [DEBUG] - got 28 proxies!
2017-10-15 23:02:47,100: (thepiratebay.py->check_proxy #70): [DEBUG] - Trying proxy: https://thepiratebay.org
2017-10-15 23:02:48,053: (Common.py->http_request #91): [DEBUG] - returned status code: 200 for url https://thepiratebay.org
2017-10-15 23:02:48,066: (thepiratebay.py->check_proxy #84): [DEBUG] - Carrying out test for string 'hello'
2017-10-15 23:02:49,067: (Common.py->http_request #91): [DEBUG] - returned status code: 200 for url https://thepiratebay.org/search/hello/0/99/0
2017-10-15 23:02:49,102: (thepiratebay.py->check_proxy #90): [DEBUG] - Test passed!
2017-10-15 23:02:49,712: (Common.py->http_request_time #65): [DEBUG] - returned status code: 200 for url https://thepiratebay.org/search/test/0/99/0
2017-10-15 23:02:49,743: (thepiratebay.py->get_html #113): [DEBUG] - fetching page 1/1
2017-10-15 23:02:49,743: (thepiratebay.py->get_html #115): [DEBUG] - page fetched in 0.61 sec!
2017-10-15 23:02:49,806: (thepiratebay.py->parse_html #212): [DEBUG] - Results fetched successfully!
2017-10-15 23:02:49,812: (thepiratebay.py->parse_html #215): [ERROR] - 'ascii' codec can't encode character '\xa0' in position 607: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/torrench/modules/thepiratebay.py", line 213, in parse_html
    self.show_output(masterlist, self.output_headers)
  File "/usr/lib/python3.6/site-packages/torrench/utilities/Common.py", line 150, in show_output
    print("\n%s" %self.output)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 607: ordinal not in range(128)
`
here's the log for it

**Comment by kryptxy** [comment]
It's more of a system (setup) issue. I am on Arch too - and never got this error.
Which desktop Environment (and terminal) are you using?
I'd like you have a look at [this](https://bbs.archlinux.org/viewtopic.php?id=122497).

**Pull request closed without merging**
